[[GAP_pkg_simpcomp]]
arch = "aarch64"
git-tree-sha1 = "e565bf6471d1c9106f1d5b6c8569de9a749d38b4"
os = "macos"

    [[GAP_pkg_simpcomp.download]]
    sha256 = "f3bac6e069eb43ddd33d15711c4b543c58b08ad9db36614dc65c28c07997449c"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_simpcomp_jll.jl/releases/download/GAP_pkg_simpcomp-v200.100.1400+0/GAP_pkg_simpcomp.v200.100.1400.aarch64-apple-darwin.tar.gz"
[[GAP_pkg_simpcomp]]
arch = "aarch64"
git-tree-sha1 = "54d6b704adef40bc1a20cc61b298b71445820303"
libc = "glibc"
os = "linux"

    [[GAP_pkg_simpcomp.download]]
    sha256 = "aad7d0e5afcbbf51abbb5f8b16f637f3dacc2c7eaad319d1fdcc2ffa50365fdb"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_simpcomp_jll.jl/releases/download/GAP_pkg_simpcomp-v200.100.1400+0/GAP_pkg_simpcomp.v200.100.1400.aarch64-linux-gnu.tar.gz"
[[GAP_pkg_simpcomp]]
arch = "aarch64"
git-tree-sha1 = "7ad030ada5abaf23ba51add260ffee5871982688"
libc = "musl"
os = "linux"

    [[GAP_pkg_simpcomp.download]]
    sha256 = "5e3f6388813bc90ba8e9130f8be59b98de450a2b8a4326f36158b0cd7bef4788"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_simpcomp_jll.jl/releases/download/GAP_pkg_simpcomp-v200.100.1400+0/GAP_pkg_simpcomp.v200.100.1400.aarch64-linux-musl.tar.gz"
[[GAP_pkg_simpcomp]]
arch = "powerpc64le"
git-tree-sha1 = "4090fde7cbba890b7d84b5c29ded2f721be908a6"
libc = "glibc"
os = "linux"

    [[GAP_pkg_simpcomp.download]]
    sha256 = "298c7e6cb021b4a36991c3cb6b6cded35c18cb18cbbc2b7bdbb174e6c21e17c2"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_simpcomp_jll.jl/releases/download/GAP_pkg_simpcomp-v200.100.1400+0/GAP_pkg_simpcomp.v200.100.1400.powerpc64le-linux-gnu.tar.gz"
[[GAP_pkg_simpcomp]]
arch = "x86_64"
git-tree-sha1 = "8be6bb722eac398ee927ab374306bbae01ca8224"
os = "macos"

    [[GAP_pkg_simpcomp.download]]
    sha256 = "f2c29592626cf2ea31b398d211dcae78f419c229e648e3239939fa8be327a48d"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_simpcomp_jll.jl/releases/download/GAP_pkg_simpcomp-v200.100.1400+0/GAP_pkg_simpcomp.v200.100.1400.x86_64-apple-darwin.tar.gz"
[[GAP_pkg_simpcomp]]
arch = "x86_64"
git-tree-sha1 = "bbc4f9e54de33c46ed31015259b46ac4c590b2c2"
libc = "glibc"
os = "linux"

    [[GAP_pkg_simpcomp.download]]
    sha256 = "4e3d2ed10345f8a42fc81361ffaf7463cf4dbacac2495bb244116d68f0031bc4"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_simpcomp_jll.jl/releases/download/GAP_pkg_simpcomp-v200.100.1400+0/GAP_pkg_simpcomp.v200.100.1400.x86_64-linux-gnu.tar.gz"
[[GAP_pkg_simpcomp]]
arch = "x86_64"
git-tree-sha1 = "60d2de6bcdfad82f93c724680b7559703fb89d58"
libc = "musl"
os = "linux"

    [[GAP_pkg_simpcomp.download]]
    sha256 = "f0e96c2d7601766b0813fd00fea69fc49b742a6cfe4db46f1fd9d60cbd785ea9"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_simpcomp_jll.jl/releases/download/GAP_pkg_simpcomp-v200.100.1400+0/GAP_pkg_simpcomp.v200.100.1400.x86_64-linux-musl.tar.gz"
[[GAP_pkg_simpcomp]]
arch = "x86_64"
git-tree-sha1 = "12dd1e003dd48321986b61d42acf8f8a4811b5e8"
os = "freebsd"

    [[GAP_pkg_simpcomp.download]]
    sha256 = "29ee908fddb7c76888b28b8399a01fd34890e3360e70f4d588111c7d24dbbb7b"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_simpcomp_jll.jl/releases/download/GAP_pkg_simpcomp-v200.100.1400+0/GAP_pkg_simpcomp.v200.100.1400.x86_64-unknown-freebsd.tar.gz"
